namespace Application.Infastructure.Database.Models;

public class UserDo
{
    public required Guid Id { get; init; }

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< master
    public required string Email { get; init; }
    public required string Firstname { get; init; }
    public required string LastName { get; init; }
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
    public required string Email { get; set; }

    public required string Firstname { get; set; }

    public required string LastName { get; set; }
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> account
    public required byte[] PasswordHash { get; set; }
    public required byte[] PasswordSalt { get; set; }
    public required string Role { get; set; }

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< master
    public string? Residence { get; init; }
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
    public string? Residence { get; set; }
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> account
    public string? Description { get; init; }
    public string? PasswordLink { get; set; }
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< master
    public string? PostalCode { get; init; }
    public string? Picture { get; init; }
    public DateTime? AdminRoleExpiresAt { get; set; }
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
    public string? PostalCode { get; set; }
    public string? Picture { get; set; }
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> account

    public ICollection<UserCommunityDo> UserCommunities { get; init; } = [];
    public ICollection<CommunityAdminDo> AdminCommunities { get; init; } = [];
    public ICollection<PostDo> Posts { get; init; } = [];
    public ICollection<CommentDo> Comments { get; init; } = [];
}

